#!/bin/sh

#  8888888b.           .d888 d8b                  8888888b.                888 d8b          
#  888   Y88b         d88P"  Y8P                  888   Y88b               888 Y8P          
#  888    888         888                         888    888               888              
#  888   d88P .d88b.  888888 888                  888   d88P  8888b.   .d88888 888  .d88b.  
#  8888888P" d88""88b 888    888                  8888888P"      "88b d88" 888 888 d88""88b 
#  888 T88b  888  888 888    888      888888      888 T88b   .d888888 888  888 888 888  888 
#  888  T88b Y88..88P 888    888                  888  T88b  888  888 Y88b 888 888 Y88..88P 
#  888   T88b "Y88P"  888    888                  888   T88b "Y888888  "Y88888 888  "Y88P"  
                                                                                         

# add more args here according to preference
ARGS="--volume=60 --video=no --loop"


notification(){
# change the icon to whatever you want. Make sure your notification server 
# supports it and already configured.

# Now it will receive argument so the user can rename the radio title
# to whatever they want

	notify-send "In Onda: " "$@" --icon=media-tape
}

menu(){
	printf "1. Lofi Girl 📝🎧\n"
	printf "2. Synthwave Boy 🖥️🕹️\n"
	printf "3. Nippon Smooth 🗻🎺\n"
	printf "4. Cafè Le Blanc 🗡️👺\n"
	printf "5. Underground Tunes 🐐🌼\n"
	printf "6. Zelda & Chill 🗡️🧚\n"
	printf "7. Game Night 🎮🌃\n"
	printf "8. RTL 102.5 📻🎸\n"
	printf "9. Radio Babboleo 📻🎸\n"
	printf "10. Radio Freccia 📻🎸\n"
	printf "11. Radio Deejay 📻🎸\n"
	printf "12. Funky Soul 📻🎸\n"
	printf "13. Galaxy News Radio 📻🎸\n"
	printf "14. Radio New Vegas 📻🎸\n"
	printf "15. Diamond City Radio 📻🎸\n"
	printf "16. Appalachia Radio 📻🎸\n"
}

main() {
	choice=$(menu | rofi -dmenu -i -sync -p "Riproduci..."| cut -d. -f1)

	case $choice in
		1)
			notification "Lofi Girl 📝🎧";
            URL="https://www.youtube.com/live/jfKfPfyJRdk?feature=share"
			break
			;;
		
		2)
			notification "Synthwave Boy 🖥️🕹️";
            URL="https://www.youtube.com/live/MVPTGNGiI-4?feature=share"
			break
			;;
		
		3)
			notification "Nippon Smooth 🗻🎺";
            URL="https://youtu.be/BIZz4A39rT4"
			break
			;;
		
		4)
			notification "Cafè Le Blanc 🔪👺";
            URL="https://youtu.be/MF8RFD7tk48"
			break
			;;
		
		5)
			notification "Underground Tunes 🐐🌼";
            URL="https://youtu.be/A7vMrjsBMTI"
			break
			;;
		
		6)
			notification "Zelda & Chill 🗡️🧚";
            URL="https://youtu.be/oCaOSz13h_o"
			break
			;;
		
		7)
			notification "Game Night 🎮🌃";
            URL="https://youtu.be/JJis0sld2cM"
			break
			;;

		8)
			notification "RTL 102.5 📻🎸";
            URL="https://streamingv2.shoutcast.com/rtl-1025"
			break
			;;
		9)
			notification "Radio Babboleo 📻🎸";
            URL="https://bbl.fluidstream.eu/babboleo.aac"
			break
			;;
		10)
			notification "Radio Freccia 📻🎸";
            URL="https://streamingv2.shoutcast.com/radiofreccia"
			break
			;;
		11)
			notification "Radio Deejay 📻🎸";
            URL="https://StreamCdnB3-4c4b867c89244861ac216426883d1ad0.msvdn.net/radiodeejay/radiodeejay/master_ma.m3u8"
			break
			;;
		12)
			notification "Funky Soul 📻🎸";
            URL="https://54-funk-soul-dance.stream.laut.fm/54-funk-soul-dance?t302=2023-08-15_06-27-51&uuid=a5486b5b-c33f-42f0-9dd9-f87f06e056df"
			break
			;;
		13)
			notification "Galaxy News Radio 📻🎸";
            URL="http://fallout.fm:8000/falloutfm2.ogg"
			break
			;;
		14)
			notification "Radio New Vegas 📻🎸";
            URL="http://fallout.fm:8000/falloutfm3.ogg"
			break
			;;
		15)
			notification "Diamond City Radio 📻🎸";
            URL="http://fallout.fm:8000/falloutfm6.ogg"
			break
			;;
		16)
			notification "Radio Appalachia 📻🎸";
            URL="http://fallout.fm:8000/falloutfm10.ogg"
			break
			;;

	esac
    # run mpv with args and selected url
    # added title arg to make sure the pkill command kills only this instance of mpv
    mpv $ARGS $ADDARGS --title="radio-mpv" $URL
}

(pkill -f radio-mpv && notify-send "Riproduzione Interrotta" --icon=media-tape) || main
