#!/bin/sh

# add more args here according to preference
ARGS="--volume=60"

notification(){
# change the icon to whatever you want. Make sure your notification server 
# supports it and already configured.

# Now it will receive argument so the user can rename the radio title
# to whatever they want

	notify-send "In Onda: " "$@" --icon=media-tape
}

menu(){
	printf "1. Lofi Girl 📝🎧\n"
	printf "2. Synthwave Boy 🖥️🕹️\n"
	printf "3. Nippon Smooth 🗻🎺\n"
	printf "4. The Bootleg Boy\n"
	printf "5. Radio Spinner\n"
	printf "6. SmoothChill"
}

main() {
	choice=$(menu | rofi -dmenu -i -sync -p "Riproduci..."| cut -d. -f1)

	case $choice in
		1)
			notification "Lofi Girl 📝🎧";
            URL="https://www.youtube.com/live/jfKfPfyJRdk?feature=share"
			break
			;;
		
		2)
			notification "Synthwave Boy 🖥️🕹️";
            URL="https://www.youtube.com/live/MVPTGNGiI-4?feature=share"
			break
			;;
		
		3)
			notification "Nippon Smooth 🗻🎺";
            URL="https://www.youtube.com/live/MVPTGNGiI-4?feature=share"
			break
			;;

			
		
	esac
    # run mpv with args and selected url
    # added title arg to make sure the pkill command kills only this instance of mpv
    mpv $ARGS --title="radio-mpv" $URL
}


(pkill -f radio-mpv && notify-send "Riproduzione Interrotta" --icon=media-tape) || main
