#!/bin/sh

# add more args here according to preference
ARGS="--volume=60 --video=no --loop"


notification(){
# change the icon to whatever you want. Make sure your notification server 
# supports it and already configured.

# Now it will receive argument so the user can rename the radio title
# to whatever they want

	notify-send "In Onda: " "$@" --icon=media-tape
}

menu(){
	printf "1. Lofi Girl 📝🎧\n"
	printf "2. Synthwave Boy 🖥️🕹️\n"
	printf "3. Nippon Smooth 🗻🎺\n"
	printf "4. Cafè Le Blanc 🗡️👺\n"
	printf "5. Underground Tunes 🐐🌼\n"
	printf "6. Zelda & Chill 🗡️🧚\n"
	printf "7. Game Night 🎮🌃\n"
	printf "8. RTL 102.5 📻🎸\n"
}

main() {
	choice=$(menu | rofi -dmenu -i -sync -p "Riproduci..."| cut -d. -f1)

	case $choice in
		1)
			notification "Lofi Girl 📝🎧";
            URL="https://www.youtube.com/live/jfKfPfyJRdk?feature=share"
			break
			;;
		
		2)
			notification "Synthwave Boy 🖥️🕹️";
            URL="https://www.youtube.com/live/MVPTGNGiI-4?feature=share"
			break
			;;
		
		3)
			notification "Nippon Smooth 🗻🎺";
            URL="https://youtu.be/BIZz4A39rT4"
			break
			;;
		
		4)
			notification "Cafè Le Blanc 🔪👺";
            URL="https://youtu.be/MF8RFD7tk48"
			break
			;;
		
		5)
			notification "Underground Tunes 🐐🌼";
            URL="https://youtu.be/A7vMrjsBMTI"
			break
			;;
		
		6)
			notification "Zelda & Chill 🗡️🧚";
            URL="https://youtu.be/oCaOSz13h_o"
			break
			;;
		
		7)
			notification "Game Night 🎮🌃";
            URL="https://youtu.be/JJis0sld2cM"
			break
			;;

		8)
			notification "RTL 102.5 📻🎸";
            URL="http://shoutcast.rtl.it:3010/"
			break
			;;


			
		
	esac
    # run mpv with args and selected url
    # added title arg to make sure the pkill command kills only this instance of mpv
    mpv $ARGS $ADDARGS --title="radio-mpv" $URL
}


(pkill -f radio-mpv && notify-send "Riproduzione Interrotta" --icon=media-tape) || main
